name: Draft Release Notes

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - main  # Replace with your default branch if it's different (e.g., master)

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: '.github/release-drafter.yml'  # This is where the release drafter config is located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
