name: Draft Release Notes

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - main  # Replace with your default branch if different (e.g., master)

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: '.github/release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub Token from Secrets
